import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
src = root / "Characters/Female/Exported/Victoria.json"
out = root / "Characters/Female/Exported/Anjali.json"
data = json.loads(src.read_text())
data["name"] = "Anjali"
data["shape_keys"].update({
    "neck_small": 0.12,
    "upperarm_small": 0.08,
    "lowerarm_small": 0.08,
    "clavicle_small": 0.14,
    "breasts_big": 0.50,
    "breasts_small": 0.0,
    "breasts_lift": 0.12,
    "breasts_fall": 0.10,
    "breasts_up": 0.08,
    "breasts_down": 0.10,
    "breasts_cone_shaped": 0.04,
    "breasts_together": 0.22,
    "breasts_rotation_in": 0.16,
    "aerolare_big": 0.12,
    "aerolare_small": 0.0,
    "nipple_out": 0.10,
    "nipple_in": 0.0,
    "ribcage_big": 0.06,
    "ribcage_narrow": 0.25,
    "back_curve_in": 0.14,
    "belly_flat": 0.34,
    "belly_fat": 0.02,
    "waist_narrow": 0.46,
    "waist_wide": 0.0,
    "hip_big": 0.38,
    "hip_small": 0.0,
    "butt_big": 0.34,
    "butt_small": 0.0,
    "butt_lifted": 0.16,
    "butt_sagging": 0.04,
    "thigh_big": 0.10,
    "thigh_small": 0.0,
    "calf_big": 0.04,
    "calf_small": 0.02,
    "jaw_big": 0.0,
    "jaw_small": 0.24,
    "jaw_round": 0.36,
    "jaw_sharp": 0.10,
    "chin_forward": 0.02,
    "chin_recessed": 0.04,
    "cheekbones_high": 0.24,
    "cheekbones_low": 0.02,
    "nose_long": 0.10,
    "nose_short": 0.02,
    "nose_wide": 0.08,
    "nose_narrow": 0.14,
    "forehead_big": 0.04,
    "forehead_small": 0.02,
    "lips_thick": 0.44,
    "lips_thin": 0.0,
    "mouth_wide": 0.06,
    "mouth_narrow": 0.08,
    "ears_big": 0.0,
    "ears_small": 0.08,
    "eyebrow_head_big": 0.08,
    "eyebrow_head_small": 0.0,
    "eyebrow_body_big": 0.06,
    "eyebrow_body_small": 0.04,
    "eyedrow_tail_big": 0.02,
    "eyebrow_tail_small": 0.08,
    "eyebrow_body_curve": 0.18,
    "eyebrow_same": 0.0,
})
data["properties"].update({
    "brow_hue": 0.50,
    "brow_sat": 0.92,
    "brow_val": 0.18,
    "eyebrows_hue": 0.50,
    "eyebrows_sat": 0.95,
    "eyebrows_val": 0.20,
    "hair_hue": 0.50,
    "hair_sat": 0.92,
    "hair_val": 0.16,
    "iris_hue": 0.50,
    "iris_sat": 0.88,
    "iris_val": 0.36,
    "skin_hue": 0.50,
    "skin_sat": 1.08,
    "skin_val": 0.72,
})
data["blend_files"] = {
    "eyebrows": "",
    "hair": "long01.blend",
    "pants": "pink_panties.blend",
    "shoes": "",
    "torso_up": "pink_brassier.blend",
}
out.write_text(json.dumps(data, indent=4) + "\n")
print(f"created {out} with {len(data['shape_keys'])} morphs")
